/// Flutter icons Givt
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Givt
///      fonts:
///       - asset: fonts/Givt.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Givt {
  Givt._();

  static const _kFontFam = 'Givt';
  static const String? _kFontPkg = null;

  static const IconData givt_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dieren = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gezondheid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hulp = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kunst = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData natuur = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onderwijs = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData welzijn = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religie = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData org_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
