/// Flutter icons PAIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PAIcons
///      fonts:
///       - asset: fonts/PAIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PAIcons {
  PAIcons._();

  static const _kFontFam = 'PAIcons';
  static const String? _kFontPkg = null;

  static const IconData dieren = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onderwijs = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kunst = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religie = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gezondheid = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData natuur = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hulp = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData welzijn = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
